#!/usr/bin/env python
import os
import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

antonAscii = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW____        _        _____                 _            WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ \      | |      / ____|               | |          WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) |_   _| |_ ___| (___  _ __  _   _  __| | ___ _ __ WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ <| | | | __/ _ \\___ \| '_ \| | | |/ _` |/ _ \ '__| WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) | |_| | ||  __/____) | |_) | |_| | (_| |  __/ |   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|____/ \__, |\__\___|_____/| .__/ \__, |\__,_|\___|_|   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW        __/ |              | |     __/ |                WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW       |___/               |_|    |___/                 WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWMMMMWWMXdl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWMMMMWMMWWKoco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWMKc'dKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWXOO00KXNNWWWWWWWWWNXXXNWWMWWk',OWWWNXKKXKKKK00XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWKoccc::clodxxKWMWKklccclodONXl.lXWNKo;;;;:ccloodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNxdKXK0kxdlc,':dKO:,,''',,';dk,'kNXk:';cdO0XK00KXK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWW0OXWWWWWWWNXOl,';:,''''..''';;.:0Ko,'l0NNKkxl;',:ldxOKXWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWXNWWWWWWN0OKNNOl,'''..........'ok:';dOxol;,,,;loc:,'',;ldxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNNNNK0xoc,',:lxkdc,'..........';,',:c,..':c;,;lk0XKOkxol:;,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNKOdl;,';cloc;,'',,,'','..',,,'.''....,lxOKXKkl:,:d0NWWWWNXkc:kNWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNKdc;;:loxO0XX0kdlc;,...;:;'.',,;::'...'oOXNNNNNNNKxl;;lkKNWWWWNkldXMMMWMMMMMMMMMMMMMMMMMMMMM
WWWWWWNOc:dk0XXNNXXXkc,,'''''.';c;'..';cc:..'ckKKKKKXXXXXXNX0xl::d0NWWWWNOkKWMWWMMMMMMMMMMMMMMMMMMMM
WWWWWNkoxXNNNXXXXX0o;',:odooolccc::;'......;dkOO00KKKKKXXXXXXNXOdc;oKNNNWWNKXWMMMMMMMMMMMMMMMMMMMMMM
WWWWXOkKNNNNXXXXKk:'',lk000OOOxlllolc:;,..,ckOOO0000KKKKKXXXXXXXN0l,dXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMM
WWWNKKNXXXXXXKK0o,',ckKXXKKK0OxoodxxddxdloxOKXKKKKXXXXXXXXXNNNNNNWXo;kWWWWMMMWMMMMMMMMMMMMMMMMMMMMMM
WWWWNNXXXXNNNXOc,';xKNXXKK00OOxodO00000KKKXXXNNNNNNNNNNNNNNNNNNWWWWNdc0WWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNWXx;',l0XXXKKKK0000xokKKXKKKXXXXXNNNNNNNNNNNNNNNNNNNNWWWWNkdXWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNW0;.;xKXXKKKKKKKKKKkoOXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNWNWWWNOONMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWNWk,,dXXXXKKKKKKXXXXo;kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNWNWWXXWMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNXo'lKXXXXKKKXXXNNNXl'xNNNNNNNNWWWWNWWWWWWNNNNNNNNNWW|---------------------------|MMMMMMMM
WWWWWWWNNNNKc;ONXXXXKXXXXNNNNWx,xNNNNNNWWWWWWWWWWWWWWWWWWWWWWWW|>>encrypt to encrypt path  |MMMMMMMM
WWWWWWNNNNNO:dXXXXXXXXNNNNNNNWO:xNNNNNWWWWWWWWWWWWWWWWWWWWWWWWW|>>decrypt to decrypt path  |MMMMMMMM
WWWWWWNNNXNkoKNXXNNNNNNNNNNWWWKlxNNNNNWWWWWWWWWWWWWWWWWWWWMMMMM|>>exit to quit to terminal |MMMMMMMM
WWWWWWNNNNXkONNNNNNNNNNNNWWWWWXdkNNNWWWWWWWWWWWWWWWWWWWWWWMMMMM|___________________________|MMMMMMMM
WWWWWWWWWWXKXWNNNNNNNNNNNNWWWWNkkNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
>>"""

directoryEncryptAnton = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW____        _        _____                 _            WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ \      | |      / ____|               | |          WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) |_   _| |_ ___| (___  _ __  _   _  __| | ___ _ __ WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ <| | | | __/ _ \\___ \| '_ \| | | |/ _` |/ _ \ '__| WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) | |_| | ||  __/____) | |_) | |_| | (_| |  __/ |   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|____/ \__, |\__\___|_____/| .__/ \__, |\__,_|\___|_|   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW        __/ |              | |     __/ |                WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW       |___/               |_|    |___/                 WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWMMMMWWMXdl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWMMMMWMMWWKoco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWMKc'dKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWXOO00KXNNWWWWWWWWWNXXXNWWMWWk',OWWWNXKKXKKKK00XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWKoccc::clodxxKWMWKklccclodONXl.lXWNKo;;;;:ccloodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNxdKXK0kxdlc,':dKO:,,''',,';dk,'kNXk:';cdO0XK00KXK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWW0OXWWWWWWWNXOl,';:,''''..''';;.:0Ko,'l0NNKkxl;',:ldxOKXWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWXNWWWWWWN0OKNNOl,'''..........'ok:';dOxol;,,,;loc:,'',;ldxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNNNNK0xoc,',:lxkdc,'..........';,',:c,..':c;,;lk0XKOkxol:;,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNKOdl;,';cloc;,'',,,'','..',,,'.''....,lxOKXKkl:,:d0NWWWWNXkc:kNWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNKdc;;:loxO0XX0kdlc;,...;:;'.',,;::'...'oOXNNNNNNNKxl;;lkKNWWWWNkldXMMMWMMMMMMMMMMMMMMMMMMMMM
WWWWWWNOc:dk0XXNNXXXkc,,'''''.';c;'..';cc:..'ckKKKKKXXXXXXNX0xl::d0NWWWWNOkKWMWWMMMMMMMMMMMMMMMMMMMM
WWWWWNkoxXNNNXXXXX0o;',:odooolccc::;'......;dkOO00KKKKKXXXXXXNXOdc;oKNNNWWNKXWMMMMMMMMMMMMMMMMMMMMMM
WWWWXOkKNNNNXXXXKk:'',lk000OOOxlllolc:;,..,ckOOO0000KKKKKXXXXXXXN0l,dXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMM
WWWNKKNXXXXXXKK0o,',ckKXXKKK0OxoodxxddxdloxOKXKKKKXXXXXXXXXNNNNNNWXo;kWWWWMMMWMMMMMMMMMMMMMMMMMMMMMM
WWWWNNXXXXNNNXOc,';xKNXXKK00OOxodO00000KKKXXXNNNNNNNNNNNNNNNNNNWWWWNdc0WWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNWXx;',l0XXXKKKK0000xokKKXKKKXXXXXNNNNNNNNNNNNNNNNNNNNWWWWNkdXWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNW0;.;xKXXKKKKKKKKKKkoOXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNWNWWWNOONMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWNWk,,dXXXXKKKKKKXXXXo;kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNWNWWXXWMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNXo'lKXXXXKKKXXXNNNXl'xNNNNNNNNWWWWNWWWWWWNNNNNNNNNWWMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNNNNKc;ONXXXXKXXXXNNNNWx,xNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNNO:dXXXXXXXXNNNNNNNWO:xNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNXNkoKNXXNNNNNNNNNNWWWKlxNNNNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNXkONNNNNNNNNNNNWWWWWXdkNNNWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWXKXWNNNNNNNNNNNNWWWWNkkNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// ENTER THE PATH THAT YOU WISH TO ENCRYPT // >> """

passwordEncryptAnton = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW____        _        _____                 _            WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ \      | |      / ____|               | |          WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) |_   _| |_ ___| (___  _ __  _   _  __| | ___ _ __ WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ <| | | | __/ _ \\___ \| '_ \| | | |/ _` |/ _ \ '__| WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) | |_| | ||  __/____) | |_) | |_| | (_| |  __/ |   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|____/ \__, |\__\___|_____/| .__/ \__, |\__,_|\___|_|   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW        __/ |              | |     __/ |                WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW       |___/               |_|    |___/                 WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWMMMMWWMXdl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWMMMMWMMWWKoco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWMKc'dKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWXOO00KXNNWWWWWWWWWNXXXNWWMWWk',OWWWNXKKXKKKK00XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWKoccc::clodxxKWMWKklccclodONXl.lXWNKo;;;;:ccloodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNxdKXK0kxdlc,':dKO:,,''',,';dk,'kNXk:';cdO0XK00KXK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWW0OXWWWWWWWNXOl,';:,''''..''';;.:0Ko,'l0NNKkxl;',:ldxOKXWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWXNWWWWWWN0OKNNOl,'''..........'ok:';dOxol;,,,;loc:,'',;ldxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNNNNK0xoc,',:lxkdc,'..........';,',:c,..':c;,;lk0XKOkxol:;,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNKOdl;,';cloc;,'',,,'','..',,,'.''....,lxOKXKkl:,:d0NWWWWNXkc:kNWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNKdc;;:loxO0XX0kdlc;,...;:;'.',,;::'...'oOXNNNNNNNKxl;;lkKNWWWWNkldXMMMWMMMMMMMMMMMMMMMMMMMMM
WWWWWWNOc:dk0XXNNXXXkc,,'''''.';c;'..';cc:..'ckKKKKKXXXXXXNX0xl::d0NWWWWNOkKWMWWMMMMMMMMMMMMMMMMMMMM
WWWWWNkoxXNNNXXXXX0o;',:odooolccc::;'......;dkOO00KKKKKXXXXXXNXOdc;oKNNNWWNKXWMMMMMMMMMMMMMMMMMMMMMM
WWWWXOkKNNNNXXXXKk:'',lk000OOOxlllolc:;,..,ckOOO0000KKKKKXXXXXXXN0l,dXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMM
WWWNKKNXXXXXXKK0o,',ckKXXKKK0OxoodxxddxdloxOKXKKKKXXXXXXXXXNNNNNNWXo;kWWWWMMMWMMMMMMMMMMMMMMMMMMMMMM
WWWWNNXXXXNNNXOc,';xKNXXKK00OOxodO00000KKKXXXNNNNNNNNNNNNNNNNNNWWWWNdc0WWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNWXx;',l0XXXKKKK0000xokKKXKKKXXXXXNNNNNNNNNNNNNNNNNNNNWWWWNkdXWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNW0;.;xKXXKKKKKKKKKKkoOXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNWNWWWNOONMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWNWk,,dXXXXKKKKKKXXXXo;kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNWNWWXXWMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNXo'lKXXXXKKKXXXNNNXl'xNNNNNNNNWWWWNWWWWWWNNNNNNNNNWWMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNNNNKc;ONXXXXKXXXXNNNNWx,xNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNNO:dXXXXXXXXNNNNNNNWO:xNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNXNkoKNXXNNNNNNNNNNWWWKlxNNNNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNXkONNNNNNNNNNNNWWWWWXdkNNNWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWXKXWNNNNNNNNNNNNWWWWNkkNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// ENTER THE ENCRYPTION PASSWORD YOU WISH TO USE // >> """

directoryDecryptAnton = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW____        _        _____                 _            WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ \      | |      / ____|               | |          WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) |_   _| |_ ___| (___  _ __  _   _  __| | ___ _ __ WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ <| | | | __/ _ \\___ \| '_ \| | | |/ _` |/ _ \ '__| WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) | |_| | ||  __/____) | |_) | |_| | (_| |  __/ |   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|____/ \__, |\__\___|_____/| .__/ \__, |\__,_|\___|_|   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW        __/ |              | |     __/ |                WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW       |___/               |_|    |___/                 WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWMMMMWWMXdl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWMMMMWMMWWKoco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWMKc'dKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWXOO00KXNNWWWWWWWWWNXXXNWWMWWk',OWWWNXKKXKKKK00XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWKoccc::clodxxKWMWKklccclodONXl.lXWNKo;;;;:ccloodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNxdKXK0kxdlc,':dKO:,,''',,';dk,'kNXk:';cdO0XK00KXK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWW0OXWWWWWWWNXOl,';:,''''..''';;.:0Ko,'l0NNKkxl;',:ldxOKXWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWXNWWWWWWN0OKNNOl,'''..........'ok:';dOxol;,,,;loc:,'',;ldxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNNNNK0xoc,',:lxkdc,'..........';,',:c,..':c;,;lk0XKOkxol:;,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNKOdl;,';cloc;,'',,,'','..',,,'.''....,lxOKXKkl:,:d0NWWWWNXkc:kNWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNKdc;;:loxO0XX0kdlc;,...;:;'.',,;::'...'oOXNNNNNNNKxl;;lkKNWWWWNkldXMMMWMMMMMMMMMMMMMMMMMMMMM
WWWWWWNOc:dk0XXNNXXXkc,,'''''.';c;'..';cc:..'ckKKKKKXXXXXXNX0xl::d0NWWWWNOkKWMWWMMMMMMMMMMMMMMMMMMMM
WWWWWNkoxXNNNXXXXX0o;',:odooolccc::;'......;dkOO00KKKKKXXXXXXNXOdc;oKNNNWWNKXWMMMMMMMMMMMMMMMMMMMMMM
WWWWXOkKNNNNXXXXKk:'',lk000OOOxlllolc:;,..,ckOOO0000KKKKKXXXXXXXN0l,dXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMM
WWWNKKNXXXXXXKK0o,',ckKXXKKK0OxoodxxddxdloxOKXKKKKXXXXXXXXXNNNNNNWXo;kWWWWMMMWMMMMMMMMMMMMMMMMMMMMMM
WWWWNNXXXXNNNXOc,';xKNXXKK00OOxodO00000KKKXXXNNNNNNNNNNNNNNNNNNWWWWNdc0WWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNWXx;',l0XXXKKKK0000xokKKXKKKXXXXXNNNNNNNNNNNNNNNNNNNNWWWWNkdXWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNW0;.;xKXXKKKKKKKKKKkoOXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNWNWWWNOONMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWNWk,,dXXXXKKKKKKXXXXo;kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNWNWWXXWMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNXo'lKXXXXKKKXXXNNNXl'xNNNNNNNNWWWWNWWWWWWNNNNNNNNNWWMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNNNNKc;ONXXXXKXXXXNNNNWx,xNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNNO:dXXXXXXXXNNNNNNNWO:xNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNXNkoKNXXNNNNNNNNNNWWWKlxNNNNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNXkONNNNNNNNNNNNWWWWWXdkNNNWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWXKXWNNNNNNNNNNNNWWWWNkkNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// ENTER THE PATH THAT YOU WISH TO DECRYPT // >> """

passwordDecryptAnton = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW____        _        _____                 _            WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ \      | |      / ____|               | |          WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) |_   _| |_ ___| (___  _ __  _   _  __| | ___ _ __ WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|  _ <| | | | __/ _ \\___ \| '_ \| | | |/ _` |/ _ \ '__| WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW| |_) | |_| | ||  __/____) | |_) | |_| | (_| |  __/ |   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW|____/ \__, |\__\___|_____/| .__/ \__, |\__,_|\___|_|   WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW        __/ |              | |     __/ |                WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWW       |___/               |_|    |___/                 WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWMMMMWWMXdl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWMMMMWMMWWKoco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWMKc'dKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWXOO00KXNNWWWWWWWWWNXXXNWWMWWk',OWWWNXKKXKKKK00XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWKoccc::clodxxKWMWKklccclodONXl.lXWNKo;;;;:ccloodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNxdKXK0kxdlc,':dKO:,,''',,';dk,'kNXk:';cdO0XK00KXK0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWW0OXWWWWWWWNXOl,';:,''''..''';;.:0Ko,'l0NNKkxl;',:ldxOKXWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWXNWWWWWWN0OKNNOl,'''..........'ok:';dOxol;,,,;loc:,'',;ldxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWNNNNK0xoc,',:lxkdc,'..........';,',:c,..':c;,;lk0XKOkxol:;,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNKOdl;,';cloc;,'',,,'','..',,,'.''....,lxOKXKkl:,:d0NWWWWNXkc:kNWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNKdc;;:loxO0XX0kdlc;,...;:;'.',,;::'...'oOXNNNNNNNKxl;;lkKNWWWWNkldXMMMWMMMMMMMMMMMMMMMMMMMMM
WWWWWWNOc:dk0XXNNXXXkc,,'''''.';c;'..';cc:..'ckKKKKKXXXXXXNX0xl::d0NWWWWNOkKWMWWMMMMMMMMMMMMMMMMMMMM
WWWWWNkoxXNNNXXXXX0o;',:odooolccc::;'......;dkOO00KKKKKXXXXXXNXOdc;oKNNNWWNKXWMMMMMMMMMMMMMMMMMMMMMM
WWWWXOkKNNNNXXXXKk:'',lk000OOOxlllolc:;,..,ckOOO0000KKKKKXXXXXXXN0l,dXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMM
WWWNKKNXXXXXXKK0o,',ckKXXKKK0OxoodxxddxdloxOKXKKKKXXXXXXXXXNNNNNNWXo;kWWWWMMMWMMMMMMMMMMMMMMMMMMMMMM
WWWWNNXXXXNNNXOc,';xKNXXKK00OOxodO00000KKKXXXNNNNNNNNNNNNNNNNNNWWWWNdc0WWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNWXx;',l0XXXKKKK0000xokKKXKKKXXXXXNNNNNNNNNNNNNNNNNNNNWWWWNkdXWWWMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWNNW0;.;xKXXKKKKKKKKKKkoOXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNWNWWWNOONMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWNWk,,dXXXXKKKKKKXXXXo;kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNWNWWXXWMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWNNNXo'lKXXXXKKKXXXNNNXl'xNNNNNNNNWWWWNWWWWWWNNNNNNNNNWWMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWNNNNKc;ONXXXXKXXXXNNNNWx,xNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNNO:dXXXXXXXXNNNNNNNWO:xNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNXNkoKNXXNNNNNNNNNNWWWKlxNNNNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWNNNNXkONNNNNNNNNNNNWWWWWXdkNNNWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWXKXWNNNNNNNNNNNNWWWWNkkNNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// ENTER THE DECRYPTION PASSWORD YOU WISH TO TRY // >> """

def generate_key_from_password(password, salt):
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100000,
    )
    key = base64.urlsafe_b64encode(kdf.derive(password.encode()))
    return key

def encrypt_files(directory, password):
    os.system("clear")
    salt = os.urandom(16)  # Generate a random salt
    key = generate_key_from_password(password, salt)
    fernet = Fernet(key)

    files_attempted = 0
    files_successful = 0

    for root, dirs, files in os.walk(directory):
        salt_file = os.path.join(root, "salt.bin")
        if not os.path.exists(salt_file):
            with open(salt_file, "wb") as salt_write:
                salt_write.write(salt)

        for file in files:
            file_path = os.path.join(root, file)
            if file != "salt.bin":
                try:
                    with open(file_path, "rb") as original_file:
                        contents = original_file.read()
                    encrypted_contents = fernet.encrypt(contents)
                    with open(file_path, "wb") as encrypted_file:
                        encrypted_file.write(encrypted_contents)
                    print(f"{file_path}: ENCRYPTED.")
                    files_successful += 1
                except Exception as e:
                    print(f"ERROR: COULD NOT DECRYPT '{file_path}': {e}")
                files_attempted += 1

    print(f"{files_successful} OF {files_attempted} FILES SUCCESSFULLY ENCRYPTED. (press enter to continue)")
    go1 = input(">>")
    os.system("clear")

def decrypt_files():
    os.system("clear")
    directory = input(directoryDecryptAnton)
    os.system("clear")

    if not os.path.isdir(directory):
        print("INVALID DIRECTORY PATH. TRY AGAIN. (press enter to continue)")
        go2 = input(">>>")
        os.system("clear")
        return

    password = input(passwordDecryptAnton)

    files_attempted = 0
    files_successful = 0

    salt_files_to_delete = []

    for root, dirs, files in os.walk(directory):
        salt_file = os.path.join(root, "salt.bin")
        if not os.path.exists(salt_file):
            print(f"ERROR: SALT FILE NOT FOUND IN '{root}'. CANNOT DECRYPT. (press enter to continue)")
            go3 = input(">>>")
            os.system("clear")
            continue

        with open(salt_file, "rb") as salt_read:
            salt = salt_read.read()

        key = generate_key_from_password(password, salt)
        fernet = Fernet(key)

        for file in files:
            file_path = os.path.join(root, file)
            if file != "salt.bin":
                try:
                    with open(file_path, "rb") as encrypted_file:
                        contents = encrypted_file.read()
                    decrypted_contents = fernet.decrypt(contents)
                    with open(file_path, "wb") as decrypted_file:
                        decrypted_file.write(decrypted_contents)
                    print(f"{file_path}: SUCCESSFULLY DECRYPTED.")
                    files_successful += 1
                except Exception as e:
                    print(f"ERROR: COULD NOT DECRYPT '{file_path}': {e}")
                files_attempted += 1
        
        salt_files_to_delete.append(salt_file)

    for salt_file in salt_files_to_delete:
        try:
            os.remove(salt_file)
        except Exception as e:
            print(f"ERROR: COULD NOT DELETE '{salt_file}': {e}")

    print(f"{files_successful} OF {files_attempted} FILES SUCCESSFULLY DECRYPTED. (press enter to continue)")
    go4 = input(">>")
    os.system("clear")

if __name__ == "__main__":
    while True:
        operation = input(antonAscii)

        if operation == "encrypt":
            os.system("clear")
            directory = input(directoryEncryptAnton)
            os.system("clear")
            password = input(passwordEncryptAnton)
            os.system("clear")
            encrypt_files(os.path.abspath(directory), password)
        elif operation == "decrypt":
            os.system("clear")
            decrypt_files()
            os.system("clear")
        elif operation == "exit":
            os.system("clear")
            break
        else:
            print("INVALID OPERATION. (press enter to continue)")
            go5 = input(">>>")
            os.system("clear")